name: Check RSS

on:
  schedule:
    - cron: "0 22 */2 * *"
  push:
    branches:
      - main

jobs:
  check-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run check_rss.py
      run: python check_rss.py

    - name: Store last check time
      uses: actions/upload-artifact@v2
      with:
        name: last_check.json
        path: last_check.json
