name: RSS Check

on:
  schedule:
    - cron: "0 22 */2 * *"
  workflow_dispatch:

jobs:
  check_rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create check directory
      run: mkdir -p check
        
    - name: Check RSS feeds
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}  
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        python check_rss.py
        
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git diff-index --quiet HEAD || git commit -m "Update last check time"
        git push
